### ISSUE TITLE
boliviajs.com no está disponible

### ISSUE THREAD

**Issue by javlc** [BoliviaJS/website#3]
El sitio en www.boliviajs.com se vé como no disponible.

![image](https://cloud.githubusercontent.com/assets/3148402/7701339/3194444a-fdf4-11e4-9916-b4b410333e11.png)

**Comment by dev123dev123** [comment]
Si me paso lo mismo Javier, deberiamos poner un pagina q diga en construccion algo asi.

**Comment by chitopolo** [comment]
Cierto, es problema del redireccionamiento del domingo porque si entran a http://boliviajs.com/#/home todo anda bien... Ahora corregiré ese problemita!

Enviado desde mi iPhone

**Comment by chitopolo** [comment]
Arreglado! ;)

**Comment by dev123dev123** [comment]
awesome
